
# 1. Firewall
if $msg contains "firewall: " then -/var/log/iptables.log
& stop

# 2. Daemon  Haupt-Log
if $programname contains "<TARGET>" then -/var/log/<TARGET>.log
& stop

# 3. Alle MQTT-Dienste gesammelt per rexex

if $programname contains "victronmqtt"
   or $programname contains "votromqtt"
   or $programname contains "bmsmqtt"
   or $programname contains "w1mqtt"
   or $programname contains "mopekamqtt"
   or $programname contains "thetfordmqtt"
   or $programname contains "sensormqtt"
   or $programname contains "i2cmqtt"
   or $programname contains "alpicoolmqtt"
then -/var/log/sensormqtt.log
& stop
