
# Lokale Namensauflösung (LAN-only, optional)
local=/womo.horchi/
no-hosts
#addn-hosts=/etc/dnsmasq.d/hosts.conf
expand-hosts
domain=womo.horchi

log-dhcp
#log-queries
log-facility=/var/log/dnsmasq.log
