
# Lokale Namensauflösung (LAN-only, optional)
local=/womo.horchi/
no-hosts
#addn-hosts=/etc/dnsmasq.d/hosts.conf
expand-hosts
domain=womo.horchi

dhcp-host=5c:cf:7f:6f:0d:81,dht_inside,<SUBNET>.30
dhcp-host=7c:9e:bd:f9:3b:14,arduino,<SUBNET>.31
dhcp-host=94:83:c4:36:5e:49,ap,<SUBNET>.1

log-dhcp
#log-queries
log-facility=/var/log/dnsmasq.log
