# =========================
# dnsmasq OFFLINE-PROFIL
# =========================

# DNS komplett aus
port=0
no-resolv
no-poll

# DHCP aktiv, kurze Lease
dhcp-range=<SUBNET>.100,<SUBNET>.240,30s

# Router und DNS NICHT senden!!
dhcp-option=option:router
dhcp-option=option:dns-server
