#! /bin/bash

# Parameters:
#   1 - command {init|start|stop|status|toggle}
#   2 - address
#   3 - answer topic
#   4 - service

# Responce:
#   Responce in JSON Format, expected elements are_
#     type      - always SC                       (madatory / elemet type string)
#     address   - mainly taken from parameter 2   (madatory / elemet type integer)
#     kind      - kind sensor {status|value|text} (madatory / elemet type string)
#     value     -                                 (optional one of state, value or text must set / elemet type real)
#     state     -                                 (optional one of state, value or text must set / elemet type boolean)
#     text      -                                 (optional one of state, value or text must set / elemet type string)
#     unit      -                                 (optional / elemet type string)

COMMAND="$1"
ADDRESS="$2"
TOPIC="$3"
SERVICE="$4"

case "$COMMAND" in
    start)
        systemctl start --quiet ${SERVICE}
        ;;

    stop)
        systemctl stop --quiet ${SERVICE}
        ;;

    toggle)
        systemctl is-active --quiet ${SERVICE}
        if [ $? == 0 ]; then
            systemctl stop --quiet ${SERVICE}
        else
            systemctl start --quiet ${SERVICE}
        fi
        ;;

    status)
        ;;

    init)
        ;;

    *)
       echo "Usage: {start|stop|status|toggle|init}"
       ;;

esac

systemctl is-active --quiet ${SERVICE}
RETVAL="$?"

if [ ${RETVAL} == 0 ]; then
   STATE="true"
else
   STATE="false"
fi

if [ "${COMMAND}" != "init" ]; then
   mosquitto_pub -t "${TOPIC}" -m "{ \"type\":\"SC\",\"address\":${ADDRESS},\"kind\":\"status\",\"state\":${STATE} }"
fi

echo -n "{ \"type\":\"SC\",\"address\":${ADDRESS},\"kind\":\"status\",\"value\":${STATE} }"

exit ${RETVAL}
