# =========================
# dnsmasq ONLINE-PROFIL
# =========================

# DNS an
port=53
no-resolv
no-poll

server=8.8.8.8
server=8.8.4.4

# -> das funktioniert warum auch immer nicht
#    ist aber auch nicht nötig
#dhcp-option=option:router,192.168.220.1
#dhcp-option=option:dns-server,192.168.220.1
#dhcp-option=option:lease-time,12h


dhcp-range=192.168.220.100,192.168.220.240,12h
